build: restaurant.o cook.o customer.o waiter.o


clean:
	rm -f *.o #Remove object files
	#Remove executables

run:
	./bootstrap.sh $(ARGS)

restaurant.o: restaurant.c


cook.o: cook.c


customer.o: customer.c 


waiter.o: waiter.c

